// @ts-nocheck
import { _ } from '../helper.ts'

export default {
  shareText: _('推荐一个开源的 OpenClaw 多智能体工作台——智爪平台，一键搭建、便捷管理模型和 Agent，还内置 AI 助手帮你排查问题，小白也能轻松上手：https://ai.iazp.cn', 'Recommend an open-source OpenClaw multi-agent workbench — Zhizhua AI Workbench. It helps you set up quickly, manage models and Agents easily, and even includes an AI assistant for troubleshooting: https://ai.iazp.cn', '推薦一個開源的 OpenClaw 多智能體工作台——智爪平台，一鍵搭建、便捷管理模型和 Agent，還內建 AI 助手幫你排查問題，小白也能輕鬆上手：https://ai.iazp.cn', 'OpenClaw を管理しやすいオープンソースの多智能体ワークベンチ「智爪平台」をおすすめします。すばやくセットアップでき、モデルや Agent の管理も簡単で、トラブル対応用の AI アシスタントも内蔵しています: https://ai.iazp.cn', '오픈소스 OpenClaw 멀티 에이전트 워크벤치인 지조 다중 에이전트 워크벤치를 추천합니다. 빠른 구축, 모델과 Agent의 편리한 관리, 그리고 문제 해결용 AI 도우미까지 제공합니다: https://ai.iazp.cn', 'Giới thiệu một workbench đa tác tử mã nguồn mở cho OpenClaw — Zhizhua AI Workbench. Thiết lập nhanh, quản lý model và Agent thuận tiện, còn có cả trợ lý AI hỗ trợ xử lý sự cố: https://ai.iazp.cn', 'Te recomiendo un workbench multiagente open source para OpenClaw: Zhizhua AI Workbench. Permite desplegar rápido, gestionar modelos y Agents fácilmente e incluye un asistente de IA para resolver problemas: https://ai.iazp.cn', 'Recomendo um workbench multiagente open source para OpenClaw — Zhizhua AI Workbench. Ele facilita a configuração, o gerenciamento de modelos e Agents, e ainda inclui um assistente de IA para troubleshooting: https://ai.iazp.cn', 'Рекомендую open-source мультиагентную рабочую среду для OpenClaw — Zhizhua AI Workbench. Она помогает быстро развернуть систему, удобно управлять моделями и агентами, а также включает ИИ-помощника для диагностики: https://ai.iazp.cn', 'Je recommande un atelier multi-agents open source pour OpenClaw : Zhizhua AI Workbench. Il permet une mise en place rapide, une gestion simple des modèles et des Agents, et intègre un assistant IA pour le dépannage : https://ai.iazp.cn', 'Ich empfehle Zhizhua AI Workbench, eine Open-Source-Workbench für OpenClaw mit mehreren Agenten. Damit lässt sich schnell starten, Modelle und Agents bequem verwalten, und ein KI-Assistent hilft bei Problemen: https://ai.iazp.cn'),
  title: _('感谢你使用智爪平台', 'Thanks for using Zhizhua AI Workbench', '感謝你使用智爪平台', '智爪平台をご利用いただきありがとうございます', '지조 다중 에이전트 워크벤치를 사용해 주셔서 감사합니다', 'Cảm ơn bạn đã sử dụng Zhizhua AI Workbench', 'Gracias por usar Zhizhua AI Workbench', 'Obrigado por usar o Zhizhua AI Workbench', 'Спасибо, что используете Zhizhua AI Workbench', 'Merci d’utiliser Zhizhua AI Workbench', 'Danke, dass du Zhizhua AI Workbench nutzt'),
  message: _('智爪平台是一个<strong>开源、可定制</strong>的产品基座，由团队持续维护和更新。如果它帮到了你，对我们最大的鼓励就是：', 'Zhizhua AI Workbench is an <strong>open-source, customizable</strong> product base that our team maintains and updates continuously. If it helped you, the best encouragement for us is:', '智爪平台是一個<strong>開源、可定制</strong>的產品基座，由團隊持續維護和更新。如果它幫到了你，對我們最大的鼓勵就是：', '智爪平台は<strong>オープンソースでカスタマイズ可能</strong>な製品基盤であり、チームが継続的に保守・更新しています。もし役に立ったなら、私たちにとって一番の励みは次のような応援です：', '지조 다중 에이전트 워크벤치는 팀이 지속적으로 유지보수하고 업데이트하는 <strong>오픈소스·커스터마이즈 가능</strong> 제품 베이스입니다. 도움이 되었다면 가장 큰 응원은 다음과 같습니다:', 'Zhizhua AI Workbench là một nền tảng sản phẩm <strong>mã nguồn mở, có thể tùy biến</strong> được đội ngũ duy trì và cập nhật liên tục. Nếu nó giúp ích cho bạn, sự ủng hộ lớn nhất dành cho chúng tôi là:', 'Zhizhua AI Workbench es una base de producto <strong>open source y personalizable</strong> que nuestro equipo mantiene y actualiza continuamente. Si te ha ayudado, la mejor forma de apoyarnos es:', 'Zhizhua AI Workbench é uma base de produto <strong>open source e personalizável</strong>, mantida e atualizada continuamente pela nossa equipe. Se ele te ajudou, o maior incentivo para nós é:', 'Zhizhua AI Workbench — это <strong>open-source и настраиваемая</strong> продуктовая база, которую команда постоянно поддерживает и развивает. Если она вам помогла, лучшая поддержка для нас — это:', 'Zhizhua AI Workbench est une base produit <strong>open source et personnalisable</strong>, maintenue et améliorée en continu par notre équipe. Si elle vous a aidé, le meilleur encouragement pour nous est :', 'Zhizhua AI Workbench ist eine <strong>quelloffene und anpassbare</strong> Produktbasis, die unser Team kontinuierlich pflegt und weiterentwickelt. Wenn sie dir geholfen hat, ist die größte Unterstützung für uns:'),
  starTitle: _('GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star'),
  starDesc: _('点个 Star 是最直接的支持', 'Giving us a Star is the most direct support', '點個 Star 是最直接的支持', 'Star を付けてもらえるのが一番直接的な応援です', 'Star를 눌러 주는 것이 가장 직접적인 응원입니다', 'Tặng một Star là cách ủng hộ trực tiếp nhất', 'Dar una Star es la forma más directa de apoyarnos', 'Dar uma Star é a forma mais direta de apoiar', 'Поставить Star — самый прямой способ поддержки', 'Mettre une Star est le soutien le plus direct', 'Ein Star ist die direkteste Unterstützung'),
  shareTitle: _('分享给朋友', 'Share with friends', '分享給朋友', '友だちに共有', '친구에게 공유', 'Chia sẻ với bạn bè', 'Compartir con amigos', 'Compartilhar com amigos', 'Поделиться с друзьями', 'Partager avec des amis', 'Mit Freunden teilen'),
  shareDesc: _('复制推荐文案，让更多人知道', 'Copy the recommendation text to spread the word', '複製推薦文案，讓更多人知道', '紹介文をコピーして、もっと多くの人に広めましょう', '추천 문구를 복사해 더 많은 사람에게 알려 주세요', 'Sao chép lời giới thiệu để nhiều người biết hơn', 'Copia el texto de recomendación para que más gente lo conozca', 'Copie o texto de recomendação para divulgar para mais pessoas', 'Скопируйте текст рекомендации, чтобы рассказать другим', 'Copiez le texte de recommandation pour le partager autour de vous', 'Kopiere den Empfehlungstext, damit mehr Leute davon erfahren'),
  shareCopied: _('✅ 已复制，去分享吧！', '✅ Copied, go share it!', '✅ 已複製，去分享吧！', '✅ コピーしました。ぜひ共有してください！', '✅ 복사되었습니다. 이제 공유해 보세요!', '✅ Đã sao chép, hãy chia sẻ ngay!', '✅ ¡Copiado! ¡Ahora compártelo!', '✅ Copiado! Agora compartilhe!', '✅ Скопировано, поделитесь этим!', '✅ Copié, allez le partager !', '✅ Kopiert, jetzt teile es!'),
  communityLabel: _('扫码加入社区交流群，第一时间获取更新和帮助', 'Scan to join the community groups for updates and help', '掃碼加入社群交流群，第一時間獲取更新和幫助', 'QR をスキャンしてコミュニティに参加し、最新情報やサポートを受け取りましょう', 'QR 코드를 스캔해 커뮤니티 그룹에 참여하고 업데이트와 도움을 받아보세요', 'Quét mã để tham gia cộng đồng, nhận cập nhật và hỗ trợ sớm nhất', 'Escanea para unirte a la comunidad y recibir novedades y ayuda', 'Escaneie para entrar na comunidade e receber atualizações e ajuda', 'Сканируйте код, чтобы присоединиться к сообществу и получать новости и помощь', 'Scannez pour rejoindre la communauté et recevoir des mises à jour et de l’aide', 'Scanne den Code, um der Community beizutreten und Updates sowie Hilfe zu erhalten'),
  qqAlt: _('QQ 交流群', 'QQ community group', 'QQ 交流群', 'QQ コミュニティグループ', 'QQ 커뮤니티 그룹', 'Nhóm cộng đồng QQ', 'Grupo de comunidad QQ', 'Grupo da comunidade QQ', 'Сообщество QQ', 'Groupe communautaire QQ', 'QQ-Community-Gruppe'),
  qqLabel: _('QQ 群', 'QQ Group', 'QQ 群', 'QQ グループ', 'QQ 그룹', 'Nhóm QQ', 'Grupo de QQ', 'Grupo QQ', 'Группа QQ', 'Groupe QQ', 'QQ-Gruppe'),
  wechatAlt: _('微信交流群', 'WeChat community group', '微信交流群', 'WeChat コミュニティグループ', '위챗 커뮤니티 그룹', 'Nhóm cộng đồng WeChat', 'Grupo de comunidad WeChat', 'Grupo da comunidade WeChat', 'Сообщество WeChat', 'Groupe communautaire WeChat', 'WeChat-Community-Gruppe'),
  wechatLabel: _('微信群', 'WeChat Group', '微信群', 'WeChat グループ', '위챗 그룹', 'Nhóm WeChat', 'Grupo de WeChat', 'Grupo WeChat', 'Группа WeChat', 'Groupe WeChat', 'WeChat-Gruppe'),
  douyinAlt: _('抖音交流群', 'Douyin community group', '抖音交流群', 'Douyin コミュニティグループ', '도우인 커뮤니티 그룹', 'Nhóm cộng đồng Douyin', 'Grupo de comunidad Douyin', 'Grupo da comunidade Douyin', 'Сообщество Douyin', 'Groupe communautaire Douyin', 'Douyin-Community-Gruppe'),
  douyinLabel: _('抖音群', 'Douyin Group', '抖音群', 'Douyin グループ', '도우인 그룹', 'Nhóm Douyin', 'Grupo de Douyin', 'Grupo Douyin', 'Группа Douyin', 'Groupe Douyin', 'Douyin-Gruppe'),
  feishuAlt: _('飞书交流群', 'Feishu community group', '飛書交流群', 'Feishu コミュニティグループ', '피슈 커뮤니티 그룹', 'Nhóm cộng đồng Feishu', 'Grupo de comunidad Feishu', 'Grupo da comunidade Feishu', 'Сообщество Feishu', 'Groupe communautaire Feishu', 'Feishu-Community-Gruppe'),
  feishuLabel: _('飞书群', 'Feishu Group', '飛書群', 'Feishu グループ', '피슈 그룹', 'Nhóm Feishu', 'Grupo de Feishu', 'Grupo Feishu', 'Группа Feishu', 'Groupe Feishu', 'Feishu-Gruppe'),
  dismissToday: _('今日不再弹窗', 'Do not show again today', '今日不再彈窗', '今日はもう表示しない', '오늘은 다시 보지 않기', 'Hôm nay không hiển thị lại', 'No volver a mostrar hoy', 'Não mostrar novamente hoje', 'Не показывать снова сегодня', 'Ne plus afficher aujourd’hui', 'Heute nicht mehr anzeigen'),
}
